import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./../components/shared/Navbar";
import Footer from "./../components/shared/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PH Newspaper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-370 mx-auto overflow-hidden flex flex-col items-center w-full bg-[#0f0a06]">
          <Navbar></Navbar>
          <div className="py-8"></div>
          {children}
          <Footer></Footer>
          <ToastContainer></ToastContainer>
        </div>
      </body>
    </html>
  );
}
